services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
      PHP_IDE_CONFIG: serverName=nordsec
    depends_on:
      - db


  nginx:
    ports:
      - "80:80"
    image: nginx:1
    depends_on:
      - app
    volumes:
      - ./:/app
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
